### ISSUE TITLE
Scrape per year and semester

### ISSUE THREAD

**Issue by bernardobelchior** [NIAEFEUP/uporto-schedule-scrapper#22]
- [x] Allow scraping per year and per semester.
- [x] Add year to table

**Comment by miguelpduarte** [comment]
Also, change so that [this ](https://github.com/NIAEFEUP/uporto-timetable-scrapper/blob/master/scrapper/scrapper/spiders/course_spider.py#L25) isn't used anymore, or at least it is set from an env, cfg, or any type of configuration file for easier updating in the following years.
