### ISSUE TITLE
Course unit not being scraped

### ISSUE THREAD

**Issue by bernardobelchior** [NIAEFEUP/uporto-schedule-scrapper#37]
[This](https://sigarra.up.pt/fcup/pt/ucurr_geral.pesquisa_ocorr_ucs_list?pv_ano_lectivo=2017&pv_uc_codigo=&pv_uc_sigla=EGEO1001&pv_uc_nome=&pv_uc_ano=&pv_uc_periodo=&pv_curso_id=&pv_tipo_curso=&pv_lingua=&pv_tipo_avaliacao=&pv_doc_codigo=&pv_doc_sigla=&pv_doc_nome=) course unit isn't being scraped.
I still don't know if the problem is with the scraper or with sigarra itself.

**Comment by miguelpduarte** [comment]
The updated CSS selector for acronyms (`'#conteudoinner > table:first-of-type tr > td:last-child'`) is fetching the Nível: 100 (the 100 part).

Not sure if this is the problem but it's not correct anyway.

**Comment by imnotteixeira** [comment]
One possible solution is to "select" the element by refering to its brother elem which always has the text "Sigla:". Maybe this can be done with a xpath selector instead of css only (perhaps regex?)

**Comment by miguelpduarte** [comment]
After switching this line out as stated above and running the scrapper, it appears that a couple more course units were fetched, and many others now have the correct acronym.

However, despite there being a row in the course_units table representing this course unit, and the foreign key pointing to the "Licenciatura em Arquitetura Paisagista" course (one of the courses that this course_unit belongs to), this does not appear as an option in the front-end.

In order for the course unit to be associated to the several courses it belongs to, maybe the table in this course unit that displays what courses it is lectured to has to be parsed, as I cannot as of yet find an other way to do this.

I am now going to investigate why this option does not appear in the front-end despite the correct row existing in the database.

**Comment by imnotteixeira** [comment]
Just letting you guys know that this selector was giving a syntax error due to the use of "". Instead it should be : 

``` acronym = response.xpath('//div[@id="conteudoinner"]/table[@class="formulario"][1]//td[text()="Sigla:"]/following-sibling::td[1]/text()').extract_first()```

On another note, I ran the scrapper with this selector, and the results were good, meaning that most of the "problematic" course_units were fetched and some more schedules were also fetched (might, however not be correlated with this selector, being only dependent of their release in sigarra)

**Comment by miguelpduarte** [comment]
Good results all around then, presumably

Maybe this warrants making a PR? Any takers?
