### ISSUE TITLE
Handle courses that can be in different years

### ISSUE THREAD

**Issue by miguelpduarte** [NIAEFEUP/uporto-schedule-scrapper#43]
See this example: https://sigarra.up.pt/fbaup/pt/ucurr_geral.ficha_uc_view?pv_ocorrencia_id=441136

This course can be in second, third or fourth year. However, currently, the selector is only getting "2":

https://github.com/NIAEFEUP/uporto-timetable-scrapper/blob/f89bc8134f87f05c07bf57688a20bef4e747716e/scrapper/scrapper/spiders/course_unit_spider.py#L119

The fix in terms of selectors is simple, but this would affect the way that the data is stored and probably some DB constraints as well, so I'm not very sure on how to best tackle this.

(I notised this when looking at an error that the parser gave for this page: https://sigarra.up.pt/fbaup/pt/ucurr_geral.ficha_uc_view?pv_ocorrencia_id=441099 which did not yet have the table with the course years. It might also be interesting to handle this case, but without the year I also don't know where we could put the information)

**Comment by bdmendes** [comment]
@Jumaruba is this fixed now?
