### ISSUE TITLE
Handle course units that can be in several courses at once

### ISSUE THREAD

**Issue by miguelpduarte** [NIAEFEUP/uporto-schedule-scrapper#44]
For example, MSIN (https://sigarra.up.pt/feup/pt/ucurr_geral.ficha_uc_view?pv_ocorrencia_id=436845) is in both MIEEC and MI:EF, but only appears in MI:EF.

Did not dive very deep into the issue yet, but I am fairly certain that this must be a problem in DB  constraints and not in the scraping itself (although it might have to be adjusted in order to allow this relation to happen).

When the DB was conceptualized, the course units were probably only in a many-to-one relationship with the courses, and not in a many-to-many one as it appears that sometimes they are.

However, messing with the DB schema will be problematic, as this implies also touching the API most likely.

We should do so, anyway, if the transfer to use SIGARRA's API is not successful, as there is some technical debt in the DB that should be addressed - namely the fact that an internal id is used for cross-referencing tables instead of SIGARRA's ids (which makes DB truncation necessary whenever a new scraping occurs in order to have the ids make sense :upside_down_face: - see #30).
What would be best would be to use SIGARRA's ids and always use [operations that would insert or update the data if it already exists](https://stackoverflow.com/questions/4205181/insert-into-a-mysql-table-or-update-if-exists/4205207#4205207).

**Comment by bdmendes** [comment]
@Jumaruba is this fixed now?

**Comment by Jumaruba** [comment]
We've fixed it 🌞
