### ISSUE TITLE
Same classes have different IDs throughout the years

### ISSUE THREAD

**Issue by bernardobelchior** [NIAEFEUP/uporto-schedule-scrapper#5]
For example, class "1MIEIC01" has the same name in 2014 and 2017, but its IDs are different so the URL will be different. 
This is okay for the second semester of this year because IDs will be the same, but the next year will be problematic, so I propose adding a `academic_year` field to the `class` table in order to solve this problem.

Example (you must be logged into sigarra):
[Year 2014 - 1st Semester](https://sigarra.up.pt/feup/pt/hor_geral.turmas_view?pv_turma_id=204789&pv_ano_lectivo=2014&pv_periodos=1&pv_periodos=2&pv_periodos=4&pv_periodos=5&pv_periodos=8&p_semana_inicio=20140914&p_semana_fim=20140920)
[Year 2014 - 2nd Semester](https://sigarra.up.pt/feup/pt/hor_geral.turmas_view?pv_ano_lectivo=2014&pv_periodos=3&pv_turma_id=204789&p_semana_inicio=20150215&p_semana_fim=20150606)
[Year 2017 - 1st Semester](https://sigarra.up.pt/feup/pt/hor_geral.turmas_view?pv_turma_id=207783&pv_periodos=1&pv_ano_lectivo=2017)

If you check the `pv_turma_id` in the query parameter, you can conclude the same as I did.

**Comment by rafaeldamasceno** [comment]
`course_id` is FK referenced in `class`,  and `course` has a unique constraint `` UNIQUE KEY `course_id` (`course_id`,`faculty_id`,`year`) ``, so maybe it's a bit redundant.

**Comment by bernardobelchior** [comment]
Ok, I didn't know that. So now I ask the question, does it make sense to add a course to the table each year when probably there won't be any change? I think it may be better to add the `academic_year` to the class, since it is the variable here.
